name: NODE.JS CI/CD Bartek main

on:
    push:
        branches: [main]
jobs:

   test:

    name: Test on Push Bartek Fenicki
    runs-on: ubuntu-latest

    strategy:
        matrix: 
            node-version: [14.x]
    
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with: 
            fetch-depth: 0

        - name: use Node.JS ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with: 
            node-version: ${{ matrix.node-version }}
        
        - name: NPM install, build and test
          run: 
            npm install
            npm test
  

